### ISSUE TITLE
实际大小偏小

### ISSUE THREAD

**Issue by lqxue** [wildma/FontAdaptation#1]
比如在1080*1920手机上  用你自定义Textview   设置100px   运行后实际大小偏小  这样还是没有可丁可卯的实现100px的高度字体

**Comment by wildma** [comment]
@lqxue 
1. Textview的高度一般都不设置固定值，自适应即可，设置固定值的话就会导致某些场景适配字体有问题，例如场景二。
2. 我的自定义Textview是用来去除字体内边距的，你设置了固定100px，再用这个自定义Textview去除内边距，那最后显示的结果肯定是比实际的偏小。
