### ISSUE TITLE
NoPaddingTextView super.onMeasure() blocked

### ISSUE THREAD

**Issue by feng612266** [wildma/FontAdaptation#3]
use doraemonkit will monitor blocked
 //DoraemonKit
    debugImplementation 'com.didichuxing.doraemonkit:doraemonkit:1.1.7'
    releaseImplementation 'com.didichuxing.doraemonkit:doraemonkit-no-op:1.1.7'

NoPaddingTextView.java:36 blocked 1736ms
NoPaddingTextView.java:36 blocked 536ms

**Comment by wildma** [comment]
没用过该框架，不知道你的具体问题。

**Comment by feng612266** [comment]
> 
> 
> 没用过该框架，不知道你的具体问题。

就是用NoPaddingTextView时会导致卡顿,NoPaddingTextView.java:36行;如果用于列表会更明显卡顿
